name: Android CI

on:
  push:
    branches:
      - main
      - "release-branch/*"
  pull_request:
    # all PRs on all branches

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Switch to Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Clean
        run: make clean

      # Build APKs
      - name: Build Debug APK
        if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'pull_request' }}
        run: make tailscale-debug.apk
      - name: Build Release APK
        if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'pull_request' }}
        run: make tailscale-release.apk

      - name: Run tests
        run: make test

      # Upload artifacts for debugging (optional, can be removed if not needed)
      - name: Upload Debug APK Artifact
        if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: tailscale-debug.apk
          retention-days: 7
      - name: Upload Release APK Artifact
        if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: tailscale-release.apk
          retention-days: 30

      # Get version info for release APK
      - name: Get version info
        if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'pull_request' }}
        id: version
        run: |
          VERSION=$(grep VERSION_LONG tailscale.version | cut -d'=' -f2 | tr -d '"')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      # Upload Debug APK to GitHub Packages (main branch only, always as latest)
      - name: Upload Debug APK to GitHub Packages
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/vnd.android.package-archive" \
            --data-binary @tailscale-debug.apk \
            "https://maven.pkg.github.com/${{ github.repository }}/tailscale-debug/latest.apk"

      # Upload Release APK to GitHub Packages (other branches, with version)
      - name: Upload Release APK to GitHub Packages
        if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'pull_request' }}
        run: |
          VERSION="${{ steps.version.outputs.version }}-${{ steps.version.outputs.short_sha }}"
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/vnd.android.package-archive" \
            --data-binary @tailscale-release.apk \
            "https://maven.pkg.github.com/${{ github.repository }}/tailscale-release/${VERSION}.apk"
